### ISSUE TITLE
Is it possible to use fixture values in case or value lists?

### ISSUE THREAD

**Issue by svenstaro** [la10736/rstest#121]
Hey, I realize I have a somewhat weird case but bear with me. 
```rust
#[fixture]
pub fn rng() -> StdRng {
    let seed: [u8; 32] = rand::thread_rng().gen();
    let rng = StdRng::from_seed(seed);
    rng
}

#[rstest]
#[case(make_password(&mut rng))]
#[tokio::test]
async fn my_test(
    mut rng: StdRng,
    #[case] password: String,
) -> Result<()> {}
```
So I want to use the `rng()` fixture in `my_test()` but also use the resulting `rng` value in `make_password` which provides a value to my `case`.

This currently doesn't work and I suppose it's not currently intended to work. Is there any chance this could be made to work?

**Comment by la10736** [comment]
That not true in general:

```
#[fixture]
pub fn ppp() -> String {
    "ppp".to_owned()
}

fn fff(s: &str) -> String {
    format!("{}-{}", s, s)
}

#[rstest]
#[case(fff(&ppp))]
fn my_test(ppp: String, #[case] password: String) {}
```

Compile fine.

The issue here is that you use `mut rng: StdRng` but in the injecting code I remove mutability because in the standard case you would just use it in your test function but not in injecting code: that means you can have lot warning about this.

I just hacked a solution and it works but I need to shut down all warnings and check if I don't have any regression.

I'll fix it ASAP

**Comment by svenstaro** [comment]
Cool!

**Comment by svenstaro** [comment]
Can you make a patch release with this?

**Comment by svenstaro** [comment]
@la10736 friendly ping :)

**Comment by la10736** [comment]
Sorry... I missed and forget it.... I'll do a release ASAP

**Comment by la10736** [comment]
Released... sorry for the delay :(

**Comment by svenstaro** [comment]
Alright, but don't forget the tag! Thanks. :)

**Comment by la10736** [comment]
I did the tag too...

**Comment by svenstaro** [comment]
Sorry, I must've missed it. Thanks for the work! :)
