### ISSUE TITLE
Unable to use circular fixtures

### ISSUE THREAD

**Issue by oriontvv** [la10736/rstest#152]
Hi, folk! I'm trying to use fixtures which have circular dependancy:

```rust
mod test {
    use rstest::{fixture, rstest};

    #[fixture]
    fn fixture_a(fixture_b: i32) -> i32 { 42 }

    #[fixture]
    fn fixture_b(fixture_a: i32) -> i32 { -42 }

    #[rstest]
    fn test_circular_fixtures(fixture_a: i32, fixture_b: i32) {
    }
}
```

I see: 
```
thread 'test::test_circular_fixtures_work' has overflowed its stack
fatal runtime error: stack overflow
error: test failed, to rerun pass '--bin circular-rstest'

Caused by:
  process didn't exit successfully: `/Users/v.v.taranov/dev/projects/circular-rstest/target/debug/deps/circular_rstest-e98b68458e134fbb` (signal: 6, SIGABRT: process abort signal)
```
Does rstest try to build dependency graph of fixtures like an pytest and then resolve them?

**Comment by la10736** [comment]
I guess that what you really mean here is to build the dependency graph to check a circular reference and raise an explicit error.
This is really hard and need some crappy hacking because procedural macro receive just the annotated function and cannot know anything about the context. Anyway procedural macro are executed before module resolving phase so it is quite impossible to cover all cases on procedural macro expansion.

Last chance can be use a recursive function analysis and show them in your IDE but I didn't find anything about this ... just an open ticket on rust-analyzer https://github.com/rust-lang/rust-analyzer/issues/11407

Unfortunately/Fortunately rust is not python and procedural macro are not function decorators.

If you have some ideas on we can handle this let me know.

**Comment by oriontvv** [comment]
Thanks for the feedback!
>I guess that what you really mean here is to build the dependency graph to check a circular reference and raise an explicit error.
Hmm. yes, it would nice to have.  Got the point about procedural macros.

Then what do you think of about adding something like `#[once_test]`? This could instantiate the fixture once per single test and reuse it in other fixtures. I think it would solve the issue perfectly and add nice feature from pytest world.

**Comment by la10736** [comment]
You mean something like `#[once]` but with a test context instead of static.

Please can you open a new issue with a simple behavior description and provide a simple example where it can be useful.
