### ISSUE TITLE
Better name modules to avoid collisions

### ISSUE THREAD

**Issue by rukai** [la10736/rstest#165]
This compiles fine
```rust
mod foo {}

#[test]
fn foo {}
```

This fails to compile:
```rust
mod foo {}

#[rstest]
#[test]
fn foo {}
```

We could avoid this failure by adding a hardcoded random value to the end of rstest generated modules. say for example: b6c26350173545d5972e6a5aea5e666f

**Comment by la10736** [comment]
Ok... you're speaking about a case like

```rust
use rstest::*;

mod foo {}

#[rstest]
#[case()]
fn foo() {}
```
I'm not inclined to change `mod` name on expanding parametric tests because
this name is what you'll read on the test output and random or some
characters can change the test's output readability/meaning.

What I can do to avoid this rare kind of problem is to introduce a
`#[display(new_name)]` annotation. But consider that the user can simply
work around this issue by simply adding an `_` before the test name to
avoid it.


Il giorno mar 25 ott 2022 alle ore 02:59 Lucas Kent <
***@***.***> ha scritto:

**Comment by rukai** [comment]
oh yes your right, it was due to the parametric tests.

Your also right in that changing the mod name would affect the test output name.

I'm going to go ahead and close this because I think adding any new functionality to support this would just be needless complication.
Given that there is a good reason for the module having that name, I think it should be on the user to just pick a different module or test name.
Thanks for your time.
