### ISSUE TITLE
Access files in parent directory to a repo

### ISSUE THREAD

**Issue by stonecharioteer** [la10736/rstest#205]
I'm trying to use files in a folder in the root level of a repository, while the tests are in a submodule.

```
github-repo/
├─ submodule/
│  ├─ src/
│  │  ├─ lib.rs (this contains the tests)
├─ test_inputs/
```

I'm unable to use `#[files("../test_inputs/")` in the `lib.rs` file so I can glob the particular files I want in `test_inputs`, but so far, I have only been getting errors related to how I `cannot remove prefix path`. I tried giving an absolute path as well (I'd really prefer to not do this), and that didn't work either. What choices do I have here?

**Comment by la10736** [comment]
Unfortunately is not possible to use files that are not in your crate. I'll try to fix it in the next days or maybe weeks is much more realistic.

Absolute path should not work either but you can try with a link.... it could works.

**Comment by la10736** [comment]
Thx! I really appreciate your help... but I've just started to fix it. The real issue here is not to find where is the bug but understand how to define a correct behavior for these cases: every case use the file path also to build the test name to make it simple to identify what are the files involved in the failed tests. So, I cannot use the absolute path to build the tests name and every strategy that involve some kind of shrinking is wrong for some use cases.

Maybe the best is to use a path relative to crate folder but the `.` character is sanitized to fit in a valid rust `ident` (replaced by `_`). I guess that the best compromise is to replace `../` with `_UP`: with this rule a relative path like `../../some/folder/more/file.txt` become `_UP/_UP/some/folder/more/file.txt` and the sanitized name will be `_UP_UP_some_folder_more_file_txt`. Otherwise we can just ignore the `../` segments but in this case we should find the maximum common prefix of all files and then remove it from the absolute path instead of remove the crate path as is today... I don't love this approach because the tests names are not stable and can change if you add or remove some files.

**Comment by not-my-profile** [comment]
> Maybe the best is to use a path relative to crate folder but the `.` character is sanitized to fit in a valid rust `ident` (replaced by _).

I am afraid I don't understand what you mean by this sentence.

Making the paths relative to `env!("CARGO_MANIFEST_DIR")` certainly seems like the best solution to me. While it would be a breaking change I think it would be worth it. (I'd consider having `_UP_UP_UP` in test names to be confusing).

**Comment by not-my-profile** [comment]
Nevermind I just realized that this is already the case:

https://github.com/la10736/rstest/blob/c0e35a784f0ebf854955e414a65795e6f26cffcc/rstest_macros/src/parse/rstest/files.rs#L239-L245

I'm sorry I misunderstood the issue description.

> ```
> github-repo/
>├─ submodule/
>│  ├─ src/
>│  │  ├─ lib.rs (this contains the tests)
>├─ test_inputs/
>```

I very much think that this is backwards ... the test_inputs should be a submodule of the test code ... not the other way around. I don't think that this should be supported by rstest.

**Comment by la10736** [comment]
Ok ... `_UP` in test names is not the best choice but I didn't find any better way to express this behavior.
I've implemented it and I hope I'll publish a new version tomorrow ... maybe the 0.18.2: I'm considering it just a bug fix.

**Comment by la10736** [comment]
0.18.2 published

**Comment by la10736** [comment]
Ok,
can you open a new ticket for that with also a proposed syntax that we can discuss?
