### ISSUE TITLE
Support dynamic `#[values]`

### ISSUE THREAD

**Issue by tomasol** [la10736/rstest#252]
It would be nice to provide the list of values by a function:

Example:
```rs
#[derive(strum_macros::EnumIter, Debug, PartialEq)]
enum Color {
    Red,
    Green,
    Blue,
}
#[rstest]
#[test]
fn test(#[values_dyn( Color::iter() )] value: Color) {
..

```

**Comment by la10736** [comment]
As I already mentioned in lot of tickets about this topic (#29 is just one of them), Rust is not Python. When the `#[rstest]` procedural macro is processed we don't know anything about `Color` type because we are in an early stage where just the abstract syntax tree was build so we cannot process `Color::iter()` to generate the 3 test functions to compile.
