### ISSUE TITLE
Mutable Fixture

### ISSUE THREAD

**Issue by candronikos** [la10736/rstest#95]
I would like to confirm the mechanics of fixtures and how I can create them so that changes made to the value carries on to other rests.

- I am using a reqwest::Client as the output of the fixture and reusing it in all my tests.
- Each test will check if the client is authenticated and will perform the handshake if not authenticated
- The expected outcome is that I should see only a single attempt to log in and all subsequent tests merely reuse the bearer auth key produced from the test that happened to make the first request

It looks like the fixture function is evaluated for each test meaning that each test gets a new client instead.

**Comment by la10736** [comment]
Hi,
no `fixture`s are not static entry but your test will call your fixture function every times. What your looking for is something like a _static fixture_. But you can try to take a look to  la10736/rstest_fixture_cache_example that give a receipt to build something like you need.

If the `reqwest::Client` reference (in the case of static fixture you should return a `&'static reqwest::Client` should be also `mut` the thing going to be more hard... you should return a MutexGurd from your fixture and all your test stop to be parallel and become sequential.

But take a look to my example and let me know if you need more help and I try to build an exmple that fit your needs.

**Comment by la10736** [comment]
Just one more note. I don't think your test really need a mutable client reference because your tests should be independent one from each other.
So maybe the best thing is to incapsulate the authentication in fixture implementation and just return the authenticated client to all your tests 
Your example is just some little bit more completed than the simpler one that I've addresses in linked repo.

**Comment by candronikos** [comment]
The test are also intended to validate the client can be used by multiple threads. I think what you're getting at is that I should spawn these multple requests as tasks in a single test?

**Comment by la10736** [comment]
Sorry but I'm not sure what is the signature of your _function under test_. From what your are writing I guess that take a mutable reference to `Client` but now I'm not so sure. What I cannot understand now is how you can use a mutable reference across threads (mutable reference are not `Send`).

Please, can you post here your _function under test_ signature?

Anyway I'll try to update https://github.com/la10736/rstest_fixture_cache_example to address also mutable reference case.

**Comment by la10736** [comment]
Updated... let me know if fits your need.

**Comment by la10736** [comment]
Sorry... ignore linked commit .... wrong reference

**Comment by la10736** [comment]
Yes, off course... :) It cannot work.

Your fixture is an async fixture... Isn't it? Because I guess that you call some async function to get this mutex....

I've pushed on master fixture's async support just yesterday. Moreover, if client is an async fixture test should take something that implement a future of something that implement `DerefMut<Target = (AbortHandle,mpsc::Sender<ops::HaystackOp>)>`: you cannot write it with just use `impl` keyword :cry: . In this case you-re forced to use the old school generics syntax

Should be something like follow
```rust
#[rstest]
#[tokio::test]
async fn about<D, F>(mut client: F) 
    where F: std::future::Future<D>,
            D: DerefMut<Target = (AbortHandle,mpsc::Sender<ops::HaystackOp>)>
{}
```

If you would like to try with async fixture please use crate from github master branch

```
[dev-dependencies]
rstest = { git = "https://github.com/la10736/rstest" }
```

Anyway if you can post here a simple example or a repository link I can try to help you on write the correct signature. That a very interesting a useful use case.

**Comment by candronikos** [comment]
It compiles now, thanks for your help. There's another issue but I think that's unrelated

**Comment by la10736** [comment]
Can I close it now?

**Comment by candronikos** [comment]
Done!
